# Generated by Django 4.0.1 on 2024-05-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='image',
            field=models.ImageField(default='path/to/my/default/image.jpg', upload_to='image/'),
        ),
    ]
